name: Deploy Laravel API

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

          echo "=== START DEPLOY ==="

          cd ${{ secrets.APP_DIR }}

          echo "=== SAVE CURRENT COMMIT ==="
          LAST_COMMIT=$(git rev-parse HEAD)

          echo "Current commit: $LAST_COMMIT"

          echo "=== RESET LOCAL CHANGES ==="
          git reset --hard

          echo "=== FETCH & MERGE FORCED ==="
          git fetch --all


          git config user.email "deploy@server.local"
          git config user.name "Deploy Bot"

          if git merge origin/master --strategy-option theirs; then
              echo "Merge successful!"
          else
              echo "Merge failed! Rolling back..."
              git reset --hard "$LAST_COMMIT"
              exit 1
          fi

          echo "=== COMPOSER INSTALL ==="
          composer install --no-interaction --prefer-dist --optimize-autoloader

          echo "=== MIGRATIONS ==="
          php artisan migrate --force

          echo "=== OPTIMIZE ==="
          php artisan optimize:clear
          php artisan optimize

          echo "=== RELOAD PHP-FPM ==="
          sudo /bin/systemctl reload php8.2-fpm

          echo "=== DEPLOY DONE ==="

          EOF
